### ISSUE TITLE
Timeline View

### ISSUE THREAD

**Issue by andrewdacasto** [OCA/project#309] opened 2017-08-21 13:09 UTC
I have installed the timeline and web_timelin modules, however I keep receiving the following error when I select the view. I have tried deleting all tasks, and I then can slect the view and have an empty view, however when I insert 1 task, I receive the error again.

I have tried to install as many of the project modules as required, but still no joy.

Error:

Expected ';'
http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6823
Traceback:
SyntaxError: Expected ';'
   at Anonymous function (http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6823:36)
   at _.forEach (http://10.0.0.224:8069/web/content/528-c8ce360/web.assets_common.js:12:558)
   at event_data_transform (http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6823:1)
   at Anonymous function (http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6826:1142)
   at _.forEach (http://10.0.0.224:8069/web/content/528-c8ce360/web.assets_common.js:12:558)
   at on_data_loaded_2 (http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6826:1085)
   at Anonymous function (http://10.0.0.224:8069/web/content/1337-d77a06b/web.assets_backend.js:6826:922)
   at Anonymous function (http://10.0.0.224:8069/web/content/528-c8ce360/web.assets_common.js:547:661)
   at fire (http://10.0.0.224:8069/web/content/528-c8ce360/web.assets_common.js:541:278)
   at self.fireWith (http://10.0.0.224:8069/web/content/528-c8ce360/web.assets_common.js:546:198)

**Comment by pedrobaeza** [comment] 2017-08-21 14:19
You are not indicating version, but please try to reproduce the error on runbot.

**Comment by andrewdacasto** [comment] 2017-08-21 14:28
Thanks for the reply.

I am using Odoo 10.0-20170821 
And I have installed the latest project_timeline and web_timeline modules from git

I have been unable to reproduce this on runbot, and I have tried to install all the same project modules that runbot has, but I still receive the error. Should I just have to insert the Expected Date? And are there any configuration settings I need to change?

**Comment by pedrobaeza** [comment] 2017-08-21 14:40
If the problem is not reproduceable in runbot, it's due to a combination of conflicts or similar in your DB, so it can't be solved in the module itself.

I close the issue then. If you are able to reproduce it on runbot, please put the steps and I'll reopen the issue.

**Closed as completed by pedrobaeza** 2017-08-21 14:40 UTC
