### ISSUE TITLE
[10.0] project_task_material_stock creates timesheets on stock move

### ISSUE THREAD

**Issue by D4N** [OCA/project#314] opened 2017-09-07 09:12 UTC
I have observed, that when adding materials to a task using the project_task_material_stock addon and moving the respective task to the stage where the materials are consumed, it not only creates a stock move, but also automatically creates a timesheet for the user that moved the task.

How to reproduce
- Create a new project, with at least two stages and set the second stage to 'Consume Materials'
- Create a task (with the name $task_name) in the first stage and assign a user (preferably a different one than your current user)
- Add a product (let's call it $product) to the newly created task in the Materials tab with the quantity $N
- Move the task to the second stage

Expected behavior
- A stock move is executed

Actual behavior
- A stock move is executed correctly
- A timesheet is created for the user that moved the task, with the title: '$task_name: $product', assigned to the new project, with no task set and with the duration $N

The later looks very much like a bug to me, since the timesheet is created with the product quantity. I have glanced over the source code and I think the function _prepare_analytic_line (https://github.com/OCA/project/blob/10.0/project_task_material_stock/models/project_task.py#L179) is the source of this. Since this looks quite intentional (probably record the move for accounting), I suspect a configuration issue on my side. However, I have no clue what it could be.

**Comment by pedrobaeza** [comment] 2017-09-07 09:15
The idea is not to create a timesheet, but an analytic cost (which is needed for material invoicing). Are you sure that the project_id field is filled?

**Comment by D4N** [comment] 2017-09-07 09:46
Yes, it looks like it is.

I have tested this a little bit further, and when I add a customer to the project, the timesheet is not created. However, I was unable to find out where Odoo saved the analytic cost (I have looked in the accounts connected to the customer, in purchases and sales)

**Comment by D4N** [comment] 2017-09-07 10:30
Sorry, I have to take my previous comment back, adding the customer did not fix the issue. The timesheet is still created (I missed it during previous testing, as the new timesheet did not appear at the top of the list). So the issue is unfortunately still present.

I have taken a look at the official documentation (https://www.odoo.com/documentation/user/10.0/project/configuration/collaboration.html#time-management-analytic-accounts) and it mentions that analytic accounts are automatically created for new projects. However the timesheet view in the community edition (which I am running), does not have the analytic account option.

**Comment by pedrobaeza** [comment] 2017-09-07 10:36
Timesheets needs project_id field to be filled, and analytic account is deduced from the project, but the idea behind these lines (that are created by the module) is to be analytic lines only.

@cubells please take a look when you can.

**Comment by D4N** [comment] 2017-09-07 13:00
I have experimented a little bit more, and the entries are created correctly as expected. They are saved in the analytic accounts, which are of course only shown, if you enable the option 'analytic accounting' (so that's a mistake on my side).

Unfortunately, the timesheets are still automatically created. I have tried to create a new project but the issue still persists.

**Comment by D4N** [comment] 2017-09-07 14:52
I have done some debugging and stepped through the inheritance of account.analytic.line. It turns out, that the hr_timesheet module (which I have installed to keep track of timesheets) creates timesheets by inheriting from account.analytic.line, too. Thus the mystery is solved: the timesheet is created automatically (as a by-product) here: https://github.com/OCA/project/blob/10.0/project_task_material_stock/models/project_task.py#L205 as it **is** an instance of account.analytic.line.

I am honestly unsure, whether there is a way out of this. Using the account.analytic.line model to record the stock move cost in the analytic accounts is a feature that I would hate to loose. But having these stray timesheets around is also a major inconvenience.

Maybe this should be reported upstream by changing hr_timesheets?

**Comment by pedrobaeza** [comment] 2017-09-07 14:57
OK, closing.

**Closed as completed by pedrobaeza** 2017-09-07 14:57 UTC

**Comment by D4N** [comment] 2017-09-07 15:24
I might have formulated this ambiguously, but I meant, that **I** have no idea how to fix this. Not that the issue is resolved or can be only fixed upstream, maybe there is another way. But I don't know it.

**Comment by pedrobaeza** [comment] 2017-09-07 15:33
For me it is, because that's the expected behaviour. As said, they are not timesheet lines, but analytic lines if no project is written.

**Comment by D4N** [comment] 2017-09-07 15:42
I understand your point and I think you are right, what hr_timesheet does is a little unexpected. However, this addon is intended to be used with projects and then you'll often want to track the time spent. So people will be using the hr_timesheet addon from Odoo, which does things in a bad way for this addon, thus making it inconvenient to use.

I'll try to open an issue upstream and hope that they will change the behavior.

EDIT: upstream issue in Odoo: [19329](https://github.com/odoo/odoo/issues/19329).
