### ISSUE TITLE
I have installed web_timeline and project_timeline but I didn't get anything

### ISSUE THREAD

**Issue by mclimentd** [OCA/project#581] opened 2019-09-23 08:16 UTC
I have tried to install web_time and project_timeline in odoo so many times but I've never seen the clock in the project view.

My Operating system is Linux Debian.

With others applications, I followed the same instructions, and the applications appear when I update the application  list.

In the demo site, I have seen that web_timeline and project_timeline don't appear but everything works.

**Comment by pedrobaeza** [comment] 2019-09-23 08:17
Restart the server and reload page with `Ctrl+F5`. You are not indicating any way how you are installing the module.

**Comment by mclimentd** [comment] 2019-09-23 13:12
First I have download the web_timeline and project_timeline from https://www.odoo.com/apps/modules/11.0/web_timeline/

When I have the file, I put it in /opt/odoo, and unzip it
unzip web_timeline-11.0.1.4.2.zip

After that, I go to /usr/lib/python3/dist-packages/odoo/addons/, and create a symbolic link to the directory web_timeline

cd /usr/lib/python3/dist-packages/odoo/addons/

ln -s /opt/odoo/web_timeline

Finally, I restart the odoo service /etc/init.d/odoo restart and go to the applications view to update the application list. At this point, nothing happens

In addition, I go to the project view, but the clock icon doesn't appear.

**Comment by pedrobaeza** [comment] 2019-09-23 13:43
Of course until you install the module, nothing will happened. The problem seems to be on your deployment, that is a bit strange to put things on that path instead of adding another folder to addons_path configuration. Any way, probably the permissions of the files are not the proper ones to be seen by odoo service.

**Comment by mclimentd** [comment] 2019-09-23 14:07
After reading your advice, I've created another folder for my addons, and I've put a line in /etc/odoo/odoo.conf 
addons_path = /opt/odoo
Then I have removed all symbolic links

... but it is still not working

**Comment by pedrobaeza** [comment] 2019-09-23 14:09
And the permissions?

**Comment by mclimentd** [comment] 2019-09-23 14:11
chmod 777 /opt/odoo/web_timeline -R

**Comment by mclimentd** [comment] 2019-09-23 14:12
drwxrwxrwx  6 root root 4096 sep 23 16:02 .
drwxr-xr-x 13 root root 4096 sep 23 16:02 ..
drwxrwxrwx  2 root root 4096 sep 23 16:02 i18n
-rwxrwxrwx  1 root root  142 may 28 23:33 __init__.py
-rwxrwxrwx  1 root root  715 jun 27 23:05 __manifest__.py
drwxrwxrwx  3 root root 4096 sep 23 16:08 models
-rwxrwxrwx  1 root root 7250 may 28 23:33 README.rst
drwxrwxrwx  5 root root 4096 sep 21 21:12 static
drwxrwxrwx  2 root root 4096 sep 23 16:02 views

**Comment by mclimentd** [comment] 2019-09-23 14:14
When I installed auditlog, it all worked fine

**Comment by pedrobaeza** [comment] 2019-09-23 14:16
Yes, but the problem is not of the module, but your deployment method. You can check that is perfectly working on runbot instance: https://runbot.odoo-community.org/runbot/140/11.0 (admin/admin). Download the version from GitHub, not from Odoo apps, check permissions, check that the addon folder is properly recognized, check that the module is listed, etc.

We can't help you more as this issue tracker is for problem with modules theirselves, not other things, but for deference, I have given you several hints, so closing.

**Closed as completed by pedrobaeza** 2019-09-23 14:16 UTC
